name: HTML5

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Kha
      run: git clone --recursive https://github.com/Kode/Kha
    - name: Get websites
      run: git clone -b editor https://github.com/mundusnine/websites.git
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin.git --depth 1
    - name: Setup Node.js 
      run: nodejs_bin/copysysbin.sh
    - name: Get Empty
      run: git clone https://github.com/foundry2D/Empty.git
    - name: Get Foundsdk
      run: cd Empty/Libraries && git clone --recursive https://github.com/foundry2D/foundsdk.git
    - name: Compile
      run:  cd Empty && ../nodejs_bin/node ../Kha/make.js -t html5 --debug
    - name: Copy build files
      run:  cp -r Empty/build/html5/* websites/sites/foundry/generated
    - name: Copy listTraits
      run:  cp -r Empty/Assets/listTraits.json websites/sites/foundry/generated/listTraits.json
    - name: Set name
      run: git config --global user.name "foundbot"
    - name: Set email
      run: git config --global user.email "foundry2dbot@gmail.com"
    - name: Git add
      run: cd ./websites && git add *
    - name: Commit binary
      run: cd ./websites && git commit -a -m "Update editor binary to $GITHUB_SHA."
    - name: Tag binary
      run: cd ./websites && git tag editor_update_$GITHUB_SHA
    - name: Push binary
      run: cd ./websites && git push https://foundbot:$FOUNDBOT_PASS@github.com/mundusnine/websites.git editor --tags
      env:
        FOUNDBOT_PASS: ${{ secrets.FOUNDBOT_PASS }}
