name: HTML5Library(WebGL)

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get Kha
      run: git clone --recursive https://github.com/Kode/Kha
    - name: Get websites
      run: git clone -b editor https://github.com/mundusnine/websites.git
    - name: Get Node.js
      run: git clone https://github.com/Kode/nodejs_bin.git --depth 1
    - name: Setup Node.js 
      run: nodejs_bin/copysysbin.sh
    - name: Get Empty
      run: git clone https://github.com/foundry2D/Empty.git
    - name: Cd into Libraries
      run: cd Empty/Libraries
    - name: Get Foundsdk
      run: git clone --recursive https://github.com/foundry2D/foundsdk.git && cd ..
    - name: Compile
      run:  ../nodejs_bin/node ../Kha/make.js -t html5 --debug
    - name: Ls build 
      run: ls ./Empty/build/html5
    - name: Copy wasm binary
      run:  cp ./build/kore.wasm Kinc_bin/Kinc_webgl.wasm
    - name: Copy js binary
      run:  cp ./build/kore.js Kinc_bin/Kinc_webgl.js
    - name: Set name
      run: git config --global user.name "foundbot"
    - name: Set email
      run: git config --global user.email "foundry2dbot@gmail.com"
    - name: Commit binary
      run: git -C Kinc_bin commit -a -m "Update HTML5 Webgl binary to $GITHUB_SHA."
    - name: Tag binary
      run: git -C Kinc_bin tag html5_webgl_$GITHUB_SHA
    - name: Pull before push
      run: git -C Kinc_bin pull
    - name: Push binary
      run: git -C Kinc_bin push https://foundbot:$FOUNDBOT_PASS@github.com/Kode-Community/Kinc_bin.git master --tags
      env:
        FOUNDBOT_PASS: ${{ secrets.FOUNDBOT_PASS }}
